apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-64xp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-64xp
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-64xp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-64xp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-64xp
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-dpks-tenant/dotnet-component/devfile-sample-dotnet60-basic-64xp@sha256:3d52502eab0c942c6ffa63215ea345cfae7e29760ffd71a749e5c588d9e5822d
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
